### ISSUE TITLE
Periodic Frame Period

### ISSUE THREAD

**Issue by rtsledge** [Mechanical-Advantage/URCL#3]
When using URCL should the Periodic Frame Periods be changed to get better data?   

i.e. calling .SetPeriodicFramePeriod() with 4 or 5 ms periods rather then the default?

**Comment by jwbonner** [comment]
URCL will capture periodic data at whatever rate the frames are published the Spark. This can be customized however you see fit depending on the application. It may be useful to use a smaller period (more samples) while running a SysId characterization on a fast mechanism or to use a longer period (fewer samples) while running during a match to reduce CAN utilization.

**Comment by rtsledge** [comment]
Sounds good.    I have added .SetXXX to my application code to increase.
